artifacts_root: artifacts_new

data_ingestion_config:
  root_dir: artifacts_new/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/blob/master/samsumdata.zip
  local_data_file: artifacts_new/data_ingestion/data.zip
  unzip_dir: artifacts_new/data_ingestion

data_validation:
  root_dir: artifacts_new/data_validation
  STATUS_FILE: artifacts_new/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]



data_transformation:
  root_dir: artifacts_new/data_transformation
  data_path: artifacts_new/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail


model_trainer:
  root_dir: artifacts_new/model_trainer
  data_path: artifacts_new/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail
  hf_token: c98e24f251d885e402cac98c4ade77cba2c19568
  # Training parameters
  num_train_epochs: 1
  warmup_steps: 0
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  weight_decay: 0.01
  logging_steps: 1000
  evaluation_strategy: steps
  eval_steps: 500
  gradient_accumulation_steps: 16
  save_steps: 1000000
